### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by mkhennoussi** [mbitson/mcg#101]
Hi, 

Thank you very much for your tool, it is amazing :)

I don't know if you noticed it, but the website is down :(
Can you have a look please ?

Thanks a lot !

**Comment by mbitson** [comment]
Hey @mkhennoussi,

I've fixed the outage- thank you very much for alerting me. Just a note, for future users that find this issue, you may install the MCG locally and use it without the site being up. Some instructions are available in this old issue:
https://github.com/mbitson/mcg/issues/32

Thank you again! Have a good day!

**Comment by nikhildr22** [comment]
@mbitson site seems to be down from past few days. can you check? local setup instructions end up in errors, it'll be really helpful if someone can add the latest instructions to readme. Thanks
