### ISSUE TITLE
Import any code you can export

### ISSUE THREAD

**Issue by kobenauf** [mbitson/mcg#102]
It would be helpful if we could import palettes that were previously exported so I can tweak colors that were generated previously.  For example, I can export to react next (which is awesome, by the way!) but I can't import that format later.

**Comment by timgautier** [comment]
I can't find any info on the format required for import at all, nor is an explanation given if it fails. That would be a big step in the right direction. I'm trying to tweak an existing color scheme that I believe was generated with this tool, but I can't import it to take a look.

**Comment by micimize** [comment]
Adding the url to the generated output would do it:
```
/* Exported from http://mcg.mbitson.com/#!?mcgpalette0=%2300f2a5 */
```

**Comment by mbitson** [comment]
Hey there @kobenauf and @timgautier !

I know this one is three years late, but I did just improve the tool to support importing any of the code that it exports. At the moment, it's only reliable with code that this tool itself generates, permitting only light edits. If you change the format too much it may not recognize the palettes correctly. 

That being said, it supports all of the languages that it exports, so it should be helpful to any future users that are interested in this feature.

PR for this was: https://github.com/mbitson/mcg/pull/113

Thank you for the feature request!
