### ISSUE TITLE
add ability to define default/hues

### ISSUE THREAD

**Issue by aronduby** [mbitson/mcg#103]
I wish there was a way to easily specify which shade mapped to which hue (default, hue-1, hue-2, etc) so the following would be possible (taken from angular material docs)

```javascript
$mdThemingProvider.theme('default')
    .primaryPalette('pink', {
      'default': '400', // by default use shade 400 from the pink palette for primary intentions
      'hue-1': '100', // use shade 100 for the <code>md-hue-1</code> class
      'hue-2': '600', // use shade 600 for the <code>md-hue-2</code> class
      'hue-3': 'A100' // use shade A100 for the <code>md-hue-3</code> class
    })
    // If you specify less than all of the keys, it will inherit from the
    // default shades
    .accentPalette('purple', {
      'default': '200' // use shade 200 for default, and keep all other shades the same
    });
```

**Comment by mbitson** [comment]
Thank you @aronduby for this feature request! After 3 years of considering this feature, I've decided to close this issue for now.

Not all of the frameworks/tools we export to actually support this feature, it's just a couple- which would make the UI changes necessary for this a bit confusing for users that are using a framework which doesn't support this.

That being said, totally open to PRs on this if anyone is interested in it.

Sorry I couldn't get this one on there!
