### ISSUE TITLE
want to use the code in a controller

### ISSUE THREAD

**Issue by Ross-Rawlins** [mbitson/mcg#31]
I want to be able to add pass colors to a function that will generate the theme on the fly so that I can have dynamic themes in my project. Have you done this with this solution?

**Comment by mbitson** [comment]
Hey @Ross-Rawlins,

You may have your solution by now- but I wanted to point out for future users that this tool is meant to help you build the theme, it is not a solution for dynamic theme changing. 

However, here is a codepen of exactly that:
http://codepen.io/davidwolsey/pen/Qbrqoe

And an example of this being done can be seen by going through the pages in the main navigation on my own personal site:
https://mbitson.com/#/resume

Thank you!

**Comment by Ross-Rawlins** [comment]
Hey I did already solve this but thanks for getting back to me.
