### ISSUE TITLE
http://mcg.mbitson.com/ is not available

### ISSUE THREAD

**Issue by nikklass** [mbitson/mcg#32]
Your website for generating material design colors http://mcg.mbitson.com/  is currently unavailable. Any problems?

**Comment by ezkay** [comment]
yep, seems like the domain expired.. :/ too bad, it's a cool tool

**Comment by dawidhyzy** [comment]
still the same

**Comment by nikklass** [comment]
http://www.color-hex.com/color/ff3900

**Comment by dawidhyzy** [comment]
How to deploy that localy?

**Comment by nikklass** [comment]
You can deploy mbitson color generator locally.
1. Download this package locally and set it up on your local webserver e.g. on c:\wamp\www directory- https://github.com/mbitson/mcg/archive/master.zip
2. Follow these steps to install bower and user bower to install the package dependencies.
i) https://ruleoftech.com/2015/setting-up-bower-and-gulp-in-windows
ii) http://andy-carter.com/blog/a-beginners-guide-to-package-manager-bower-and-using-gulp-to-manage-components
3. Once all dependencies are installed you will have the theme generator locally!
4 You will then be able to run it via: http://localhost/mcg or wherever you set it up

**Comment by lsharir** [comment]
This one did the trick for me guys:
https://angular-md-color.com

**Comment by mbitson** [comment]
Hey Everyone!

Sorry I missed this issue, and my domain renewal, heh... busy days with work. I'll go ahead and get this back up today.

Also, @nikklass is exactly right- this package is designed to be able to be installed wherever you'd like. I'm happy you were able to get this working for you :)

**Comment by mbitson** [comment]
Aaaaand we're back! Sorry for the wait!

http://mcg.mbitson.com/
