### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by easyaspi314** [mbitson/mcg#38]
Currently, MCG suffers from ugly reformatting. It cuts off on phones. It doesn't work very well; and it isn't something to ignore: _[On-the-go](https://play.google.com/store/apps/details?id=com.aide.ui) [software](https://play.google.com/store/apps/details?id=org.kidinov.awd) [development's](https://play.google.com/store/apps/details?id=name.antonsmirnov.android.cppdroid) [a](https://play.google.com/store/apps/details?id=com.hipipal.qpyplus) [thing](https://play.google.com/store/apps/details?id=com.aide.web)._

The website isn't very complex, but if it isn't “improved”, it is going to get worse.

It would be a good idea to rework the design using a _progressive enhancement_, or _mobile-first_, responsive approach. This is starting at the bottom, the mobile site, then making the tablet site, then the desktop.

This makes for a website that is content-first and it seriously pays off, despite being difficult to begin with. CSS, and its almighty flexbox tool, makes adding content easy once you have a framework. 

I don't know Angular, but I am decent at CSS and have a basic understanding of HTML, so I could help.

**Comment by easyaspi314** [comment]
Here are some screenshots from Firefox's Responsive mode.

![screen shot 2016-05-20 at 20 14 01](https://cloud.githubusercontent.com/assets/6258309/15445097/99bf5632-1ec7-11e6-8dc9-d075b4005136.png)![screen shot 2016-05-20 at 20 14 13](https://cloud.githubusercontent.com/assets/6258309/15445099/9ca40fd2-1ec7-11e6-97dd-5f5825ee3638.png)![screen shot 2016-05-20 at 20 14 19](https://cloud.githubusercontent.com/assets/6258309/15445101/9f5f9c5a-1ec7-11e6-8166-aa6563da8fcf.png)![screen shot 2016-05-20 at 20 14 27](https://cloud.githubusercontent.com/assets/6258309/15445110/b6f4e7f8-1ec7-11e6-8158-731cc7129c49.png)![screen shot 2016-05-20 at 20 14 31](https://cloud.githubusercontent.com/assets/6258309/15445113/b9d040f8-1ec7-11e6-90ad-f7d88a74235b.png)![screen shot 2016-05-20 at 20 14 36](https://cloud.githubusercontent.com/assets/6258309/15445116/bb9f0d7e-1ec7-11e6-97b5-f5ea3d70c0fa.png)

I know a CSS trick that can shorten a title to an acronym (in a pretty cool way, too. We can make it shorten right to MCG.

I am working on mockups.

**Comment by mbitson** [comment]
Hey Man,

I appreciate the interest in the project. This is definitely correct- if mobile is a concern, build mobile first. That being said, I couldn't really imagine someone needing a mobile interface to generate a series of palettes and copy the code to their clipboard- so I prioritized this low on the list (see list in Readme of repo). Even with it being low on the list, it's definitely something I would like to add to the project. 

Any help is greatly appreciated. I follow the Gitflow branching model- so just create a PR on develop with any changes you'd like to see and I'll review. I've got some changes in the works currently for Android XML support and Material Design Lite support (SCSS). You can preview any commits that are in develop and not yet in master here:
http://mcg.mbitson.com/dev/#/

Thank you again for reviewing the tool and taking the time to provide input! It's very much appreciated.
-Mike
