### ISSUE TITLE
Ability to load theme/palettes via url parameters

### ISSUE THREAD

**Issue by atomicleopard** [mbitson/mcg#43]
Cool tool,

It would be great to encode the palettes/theme into the url somehow so I could save the link as a comment in the source code. This would allow collaborators to make small changes later by following the link and re-exporting.

**Comment by mbitson** [comment]
Hey @atomicleopard,

I'll definitely look into making this happen- it may be a minute before I can get to it, but possibly next week.

Thanks!

**Comment by mbitson** [comment]
Hey @atomicleopard,

I've just deployed a fix to the import functionality and an addition to the export functionality.

You may now go to export and select "MCG Reimport". Copy this JSON array as it is your current theme configuration.

At any time in the future your coworkers can take that snippet and click "Import", paste it into the box, and click "import". They may then adjust, reexport, and save the new snippet.

Thank you!
