### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by leocaseiro** [mbitson/mcg#44]
Hi @mbitson, are you planning to setup an Angular 2 version of the mcg?

That would be nice!

It's very similar, btw:

[src/lib/core/theming/_palette.scss](https://github.com/angular/material2/blob/e0726e15bf0fd1696e9bcb53f8d75d25ca815689/src/lib/core/theming/_palette.scss)

**Comment by mbitson** [comment]
Hey Leo!

Will absolutely plan to add this in. Thank you for the link to the example!

Cheers,
Mikel

**Comment by mbitson** [comment]
Hey @leocaseiro,

I've deployed an enhancement for this. You may now export in a matching palette SCSS format, such as:
```/* For use in src/lib/core/theming/_palette.scss */

$md-mcgpalette0: (
    '50' : #e8eaf6,
    '100' : #c5cae9,
    '200' : #9fa8da,
    '300' : #7986cb,
    '400' : #5c6bc0,
    '500' : #3f51b5,
    '600' : #3949ab,
    '700' : #303f9f,
    '800' : #283593,
    '900' : #1a237e,
    'A100' : #8c9eff,
    'A200' : #536dfe,
    'A400' : #3d5afe,
    'A700' : #304ffe,
    'contrast': (
        '50' : #000000,
        '100' : #000000,
        '200' : #000000,
        '300' : #ffffff,
        '400' : #ffffff,
        '500' : #ffffff,
        '600' : #ffffff,
        '700' : #ffffff,
        '800' : #ffffff,
        '900' : #ffffff,
        'A100' : #000000,
        'A200' : #ffffff,
        'A400' : #ffffff,
        'A700' : #ffffff,
    )
);
```

This is done by going to export and selecting "Angular JS 2 (Material 2)". 

Thank you!!

**Comment by leocaseiro** [comment]
Many thanks @mbitson

Thanks for that
