### ISSUE TITLE
700 = A700

### ISSUE THREAD

**Issue by ajsb85** [mbitson/mcg#46]
Custom color create equal values in 700 and A700 .

**Comment by mbitson** [comment]
Thank you for bringing this back up- the A series of colors are currently incorrect. I'll look into the algorithm and see what adjustments will match it up more closely with the standard.

**Comment by mbitson** [comment]
I have adjusted these to be more saturated and lighter than they were. There is no exact science for determining these colors- but I welcome any feedback on the adjustments that should be on these colors.

**Comment by ajsb85** [comment]
Thank you!
