### ISSUE TITLE
Angular 2 scss output leads to error

### ISSUE THREAD

**Issue by MA-Maddin** [mbitson/mcg#68]
> ERROR in ./\~/css-loader?sourcemap!./\~/postcss-loader!./\~/sass-loader?sourcemap!./src/my-theme.scss
> Module build failed:
> undefined
>               ^
>       Argument `$color` of `opacity($color)` must be a color
> 
> Backtrace:
>         node_modules/@angular/material/core/theming/_theming.scss:55, in function `opacity`
>         node_modules/@angular/material/core/theming/_theming.scss:55, in function `if`
>         node_modules/@angular/material/core/theming/_theming.scss:55, in function `md-color`
>         node_modules/@angular/material/core/theming/_theming.scss:51, in function `md-color`
>         node_modules/@angular/material/button/_button-theme.scss:11, in mixin `-md-button-focus-color`
>         node_modules/@angular/material/button/_button-theme.scss:58, in mixin `md-button-theme`
>         node_modules/@angular/material/core/theming/_all-theme.scss:29, in mixin `angular-material-theme`
>         stdin:89
>       in C:\my-path\node_modules\@angular\material\core\theming\_theming.scss (line 55, column 16)

It seems like an issue of material design package, but removing the `'` around the `100`, `500`, `600 `and contrast's `500`, solved the problem:

```
$md-test: (
    '50' : #f3f8f5,
    100 : #c1ddcb, // here
    '200' : #9dc9ac,
    '300' : #6fb085,
    '400' : #5ba574,
    500 : #509266, // here
    600 : #457e58, // here
    '700' : #3a6a4a,
    '800' : #30573d,
    '900' : #25432f,
    'A100' : #e8f9ee,
    'A200' : #97e4b1,
    'A400' : #57be79,
    'A700' : #53a96f,
    'contrast': (
        '50' : #000000,
        '100' : #000000,
        '200' : #000000,
        '300' : #000000,
        '400' : #000000,
        500 : #ffffff, // and here
        '600' : #ffffff,
        '700' : #ffffff,
        '800' : #ffffff,
        '900' : #ffffff,
        'A100' : #000000,
        'A200' : #000000,
        'A400' : #000000,
        'A700' : #000000,
    )
);
```

and as seen in https://github.com/angular/material2/blob/master/src/lib/core/theming/_palette.scss they don't use `'` ever ;-)

**Comment by mbitson** [comment]
Oopsie. I'll get that corrected very soon- Thank you for bringing this up!

**Comment by mbitson** [comment]
Hey @MA-Maddin ,

I got this adjusted in https://github.com/mbitson/mcg/pull/70 - which is now live on mcg.mbitson.com. New output is:

```
$md-mcgpalette0: (
    50 : #e8eaf6,
    100 : #c5cae9,
    200 : #9fa8da,
    300 : #7986cb,
    400 : #5c6bc0,
    500 : #3f51b5,
    600 : #3949ab,
    700 : #303f9f,
    800 : #283593,
    900 : #1a237e,
    A100 : #8c9eff,
    A200 : #536dfe,
    A400 : #3d5afe,
    A700 : #304ffe,
    contrast: (
        50 : #000000,
        100 : #000000,
        200 : #000000,
        300 : #ffffff,
        400 : #ffffff,
        500 : #ffffff,
        600 : #ffffff,
        700 : #ffffff,
        800 : #ffffff,
        900 : #ffffff,
        A100 : #000000,
        A200 : #ffffff,
        A400 : #ffffff,
        A700 : #ffffff,
    )
);
```

Thank you!
