### ISSUE TITLE
Can you please add vue-material

### ISSUE THREAD

**Issue by maryleloisa** [mbitson/mcg#69]
Can you please add vue-material palette format to export options. Thank you.

https://github.com/marcosmoura/vue-material/blob/f967fe912fbd4edad18ca00d4a47bce461606157/src/core/components/mdTheme/palette.js

**Comment by mbitson** [comment]
Hey @ozgureffe,

I sure can! I'll get this added soon.

Thank you for your request!

**Comment by mbitson** [comment]
Hey @ozgureffe,

Do you have any insight on how you would want this output to function? Should it be designed to be placed into that palette.js file you specified, or using some other Vue specific method to add the custom theme? I googled a bit, the best I could see was how to specify a default color in a new theme- but not how to specify new colors for a new theme. 

I can have this output as JSON for the palette.js file pretty fast, but I'd like to do this properly. Do you know how you should add a custom theme to Vue Material?

Thank you!

**Comment by maryleloisa** [comment]
Hi @mbitso.

Vue material is still in its early stages. Although there are some plans, for now, there is no smarter way to add custom palettes, except editing palette.js directly. 

For this reason, it would be enough to be able to create an output in JSON format.
I do not think that the JSON format will change much either.

Thank you so much for your interest.

**Comment by mbitson** [comment]
Hey @ozgureffe ,

I got this fixed in https://github.com/mbitson/mcg/pull/73 and deployed to the live tool. You can now export to Vue.js Material Design in the Export dialog.

Example output:
```
    mcgpalette0:{
        50: '#e8eaf6',
        100: '#c5cae9',
        200: '#9fa8da',
        300: '#7986cb',
        400: '#5c6bc0',
        500: '#3f51b5',
        600: '#3949ab',
        700: '#303f9f',
        800: '#283593',
        900: '#1a237e',
        A100: '#8c9eff',
        A200: '#536dfe',
        A400: '#3d5afe',
        A700: '#304ffe',
        darkText: [50,100,200,"A100"]
    },
```

Let me know if this works out ok for ya :) - note that assigning the palette a name will bypass the mcgpalette0 name in the example above.

Thank you!

**Comment by maryleloisa** [comment]
It worked perfectly. Until now I was doing it by hand.  Thank you :)

By the way some side notes: 
1. In the color picker there is no clue about acceptable color formats. It says rgb(,,) and I was always converting my # values to rgb() before using app. I accidentally noticed that i can use # colors.
2. When I click export button it adds another color palette besides mine. Is that necessary?
3. View code button in palette containers doesn't work. 

Thank you again.

**Comment by mbitson** [comment]
Hey @ozgureffe ,

I've fixed the single palette View Code option and prevented the theme export from requiring a second palette. This was a leftover from exporting a theme for AngularJS's Material Design framework- which requires two palettes to define a theme.

As for the color picker- I'll look at adding an info tooltip or something similar soon.

Thank you!

**Comment by mbitson** [comment]
Hey @ozgureffe ,

The default format for the color picker is now hex- you shouldn't see any RGB colors in the mix anymore. I also adjusted the color generation logic slightly to more closely match the majority of the palettes. Let me know if you run into any problems.

Thank you!
