### ISSUE TITLE
material-ui next

### ISSUE THREAD

**Issue by rosskevin** [mbitson/mcg#82]
First, thanks for an awesome tool!

We are working on `material-ui` `next` which deviates significantly from the old.  I generated a palette and only slightly modified from the Angular 2 export.

It would be awesome if you added it.  Here's the relevant bits, a simple object/hash export:
https://github.com/callemall/material-ui/blob/next/src/styles/colors.js#L17

**Comment by mbitson** [comment]
Hey @rosskevin - got it, no problem. I'll work on adding this soon!

**Comment by mbitson** [comment]
Hey @rosskevin ,

I've got this completed and pushed to production. Example output here:
```/* For use in material-ui/src/styles/colors.js */
export const mcgpalette0 = {
    50: '#e8eaf6',
    100: '#c5cae9',
    200: '#9fa8da',
    300: '#7986cb',
    400: '#5c6bc0',
    500: '#3f51b5',
    600: '#3949ab',
    700: '#303f9f',
    800: '#283593',
    900: '#1a237e',
    A100: '#8c9eff',
    A200: '#536dfe',
    A400: '#3d5afe',
    A700: '#304ffe',
    'constrastDefaultColor': 'dark',
};
```

Please let me know if you run into any problems with it/if this formatting works for you in your app.

Thank you!!
Mikel
