### ISSUE TITLE
Different generator algorithms 

### ISSUE THREAD

**Issue by scottromack** [mbitson/mcg#84]
First off this is awesome!
I need something like this on a big project I am working on.

I see in the code there are different algorithms available.
Which one is in use here => http://mcg.mbitson.com/#!/

The accent colors are too contrasty if you use a muted base color. I would like to try out the alternate algorithm ['constantin']

I'm a designer so I'm 'supposed' to be a color expert.
Thanks,

**Comment by mbitson** [comment]
Hey @ShaggyDude ,

For sure! We're currently using the constantin inspired algorithm by default. I'll add a toggle to the UI to allow you to change the algorithm very soon.

Thank you!

**Comment by mbitson** [comment]
Hey @ShaggyDude ,

I've got this in place now on the live tool. There is now a settings button that opens a sidenav with options to select which algorithm to use.

Thank you!
