### ISSUE TITLE
material-ui@next export issue

### ISSUE THREAD

**Issue by ghost** [mbitson/mcg#95]
Hi buddy,
When exporting to material-ui@next, you should write `contrastDefaultColor` and not `constrastDefaultColor`.

Thanks!

**Comment by DjLeChuck** [comment]
+1, spend 10 minutes in this because I didn't see the misprint! :smile:

**Comment by mbitson** [comment]
This has been fixed by https://github.com/mbitson/mcg/pull/97

Thank you @oliviertassinari
