### ISSUE TITLE
extract the algorithm into its own library and publish to NPM

### ISSUE THREAD

**Issue by jgoux** [mbitson/mcg#96]
Hello,

your application is really useful !

Would it be possible to extract the algorithm into its own library so we can use it directly from our projects ?

Something like : 
```js
import mcg from 'mcg'

const palette = mcg('#fefefe') // returns the object with all the generated colors
```

**Comment by jacarma** [comment]
Yes please! I would use it too

**Comment by jgoux** [comment]
@jacarma I did a little script as an experiment to do it myself : https://codesandbox.io/s/kZN3kNpQK

**Comment by tabuckner** [comment]
@mbitson Hey, I would have no problem taking care of this soon. It's the least I can do for you guys making this open source.

**Comment by tabuckner** [comment]
@jacarma @jgoux I realize this is like two years late, but I just published a quick[ sass adaptation](https://www.npmjs.com/package/mdp-sass) of the core logic for the palette generation. I'll finish up the javascript library a little later and let you guys know...even though there is probably not a use case anymore :sweat_smile:

**Comment by mbitson** [comment]
Hey @tabuckner nicely done! I like that SASS implementation 👍 

I think a NPM package would be awesome. I could see it being helpful, but I agree, probably not still applicable to the original request here lol

**Comment by mbitson** [comment]
While I am not offering an NPM package specifically, I am going to close this issue for now. It's not necessarily an issue relevant to this particular repository.

That being said, the primary tool used in determining our colors is actually the [tinycolor](https://github.com/bgrins/TinyColor) repo. 

So, if you need to generate these palettes dynamically, first run:
`npm install tinycolor2`

Once you have tinycolor setup, simply use the following to generate the array you're looking for:
```javascript
function getColorObject(value, name) {
	var c = tinycolor(value);
	return {
		name: name,
		hex: c.toHexString(),
		darkContrast: c.isLight()
	};
}
function mcg(hex){
	return [
		getColorObject(tinycolor(hex).lighten(52), '50'),
		getColorObject(tinycolor(hex).lighten(37), '100'),
		getColorObject(tinycolor(hex).lighten(26), '200'),
		getColorObject(tinycolor(hex).lighten(12), '300'),
		getColorObject(tinycolor(hex).lighten(6), '400'),
		getColorObject(tinycolor(hex), '500'),
		getColorObject(tinycolor(hex).darken(6), '600'),
		getColorObject(tinycolor(hex).darken(12), '700'),
		getColorObject(tinycolor(hex).darken(18), '800'),
		getColorObject(tinycolor(hex).darken(24), '900'),
		getColorObject(tinycolor(hex).lighten(50).saturate(30), 'A100'),
		getColorObject(tinycolor(hex).lighten(30).saturate(30), 'A200'),
		getColorObject(tinycolor(hex).lighten(10).saturate(15), 'A400'),
		getColorObject(tinycolor(hex).lighten(5).saturate(5), 'A700')
	];
}
```

Now, you can simply generate any palette you'd like using the originally requested JS snippet:
`const palette = mcg('#fefefe')`
