### ISSUE TITLE
Define accent palette

### ISSUE THREAD

**Issue by phongca22** [mbitson/mcg#99]
Primary palette is working.
How to define accent palette?

Generate 2 palettes by using your code. For accent I set contrastDefaultColor = "dark" and push "A200" to contrastDarkColors. When I use #e91e63, it create #ffc1c1.

[https://codepen.io/phongca22/pen/EXReKW/](https://codepen.io/phongca22/pen/EXReKW)

**Comment by phongca22** [comment]
When I checked generate code, I found out. The RGB is missing. So it's work ok.
I have a question. How will we define contrastDefaultColor?

**Comment by mbitson** [comment]
Hey @phongca22,

I apologize for the wait on this. I'm just now working on cleaning up this tool and addressing any concerns. Can you tell me if you're still having a problem here? 

I assume you've got this fixed on your end now, but please leave a comment if you still have problems with the tool and I'll take a look.

Thank you for your report! Again, sorry for the wait!
